// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	commonledger "github.com/hyperledger/fabric/common/ledger"
	chaincode_test "github.com/hyperledger/fabric/core/chaincode"
	pb "github.com/hyperledger/fabric/protos/peer"
)

// BuildQueryResponseWithMetaInfo(txContext *TransactionContext, iter commonledger.ResultsIterator, iterID string) (*pb.QueryResponseWithMetaInfo, error)

type QueryResponseBuilder struct {
	BuildQueryResponseStub        func(txContext *chaincode_test.TransactionContext, iter commonledger.ResultsIterator, iterID string) (*pb.QueryResponse, error)
	buildQueryResponseMutex       sync.RWMutex
	buildQueryResponseArgsForCall []struct {
		txContext *chaincode_test.TransactionContext
		iter      commonledger.ResultsIterator
		iterID    string
	}
	buildQueryResponseReturns struct {
		result1 *pb.QueryResponse
		result2 error
	}
	buildQueryResponseReturnsOnCall map[int]struct {
		result1 *pb.QueryResponse
		result2 error
	}

	BuildQueryResponseWithMetaInfoStub        func(txContext *chaincode_test.TransactionContext, iter commonledger.ResultsIterator, iterID string) (*pb.QueryResponseWithMetaInfo, error)
	buildQueryResponseWithMetaInfoMutex       sync.RWMutex
	buildQueryResponseWithMetaInfoArgsForCall []struct {
		txContext *chaincode_test.TransactionContext
		iter      commonledger.ResultsIterator
		iterID    string
	}
	buildQueryResponseWithMetaInfoReturns struct {
		result1 *pb.QueryResponseWithMetaInfo
		result2 error
	}
	buildQueryResponseWithMetaInfoReturnsOnCall map[int]struct {
		result1 *pb.QueryResponseWithMetaInfo
		result2 error
	}

	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *QueryResponseBuilder) BuildQueryResponseWithMetaInfo(txContext *chaincode_test.TransactionContext, iter commonledger.ResultsIterator, iterID string) (*pb.QueryResponseWithMetaInfo, error) {
	fake.buildQueryResponseWithMetaInfoMutex.Lock()
	ret, specificReturn := fake.buildQueryResponseWithMetaInfoReturnsOnCall[len(fake.buildQueryResponseWithMetaInfoArgsForCall)]
	fake.buildQueryResponseWithMetaInfoArgsForCall = append(fake.buildQueryResponseWithMetaInfoArgsForCall, struct {
		txContext *chaincode_test.TransactionContext
		iter      commonledger.ResultsIterator
		iterID    string
	}{txContext, iter, iterID})
	fake.recordInvocation("BuildQueryResponseWithMetaInfo", []interface{}{txContext, iter, iterID})
	fake.buildQueryResponseWithMetaInfoMutex.Unlock()
	if fake.BuildQueryResponseWithMetaInfoStub != nil {
		return fake.BuildQueryResponseWithMetaInfoStub(txContext, iter, iterID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.buildQueryResponseWithMetaInfoReturns.result1, fake.buildQueryResponseWithMetaInfoReturns.result2
}

func (fake *QueryResponseBuilder) BuildQueryResponseWithMetaInfoCallCount() int {
	fake.buildQueryResponseWithMetaInfoMutex.RLock()
	defer fake.buildQueryResponseWithMetaInfoMutex.RUnlock()
	return len(fake.buildQueryResponseWithMetaInfoArgsForCall)
}

func (fake *QueryResponseBuilder) BuildQueryResponseWithMetaInfoArgsForCall(i int) (*chaincode_test.TransactionContext, commonledger.ResultsIterator, string) {
	fake.buildQueryResponseWithMetaInfoMutex.RLock()
	defer fake.buildQueryResponseWithMetaInfoMutex.RUnlock()
	return fake.buildQueryResponseWithMetaInfoArgsForCall[i].txContext, fake.buildQueryResponseWithMetaInfoArgsForCall[i].iter, fake.buildQueryResponseWithMetaInfoArgsForCall[i].iterID
}

func (fake *QueryResponseBuilder) BuildQueryResponseWithMetaInfoReturns(result1 *pb.QueryResponseWithMetaInfo, result2 error) {
	fake.BuildQueryResponseWithMetaInfoStub = nil
	fake.buildQueryResponseWithMetaInfoReturns = struct {
		result1 *pb.QueryResponseWithMetaInfo
		result2 error
	}{result1, result2}
}

func (fake *QueryResponseBuilder) BuildQueryResponseWithMetaInfoReturnsOnCall(i int, result1 *pb.QueryResponseWithMetaInfo, result2 error) {
	fake.BuildQueryResponseWithMetaInfoStub = nil
	if fake.buildQueryResponseWithMetaInfoReturnsOnCall == nil {
		fake.buildQueryResponseWithMetaInfoReturnsOnCall = make(map[int]struct {
			result1 *pb.QueryResponseWithMetaInfo
			result2 error
		})
	}
	fake.buildQueryResponseWithMetaInfoReturnsOnCall[i] = struct {
		result1 *pb.QueryResponseWithMetaInfo
		result2 error
	}{result1, result2}
}

func (fake *QueryResponseBuilder) BuildQueryResponse(txContext *chaincode_test.TransactionContext, iter commonledger.ResultsIterator, iterID string) (*pb.QueryResponse, error) {
	fake.buildQueryResponseMutex.Lock()
	ret, specificReturn := fake.buildQueryResponseReturnsOnCall[len(fake.buildQueryResponseArgsForCall)]
	fake.buildQueryResponseArgsForCall = append(fake.buildQueryResponseArgsForCall, struct {
		txContext *chaincode_test.TransactionContext
		iter      commonledger.ResultsIterator
		iterID    string
	}{txContext, iter, iterID})
	fake.recordInvocation("BuildQueryResponse", []interface{}{txContext, iter, iterID})
	fake.buildQueryResponseMutex.Unlock()
	if fake.BuildQueryResponseStub != nil {
		return fake.BuildQueryResponseStub(txContext, iter, iterID)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.buildQueryResponseReturns.result1, fake.buildQueryResponseReturns.result2
}

func (fake *QueryResponseBuilder) BuildQueryResponseCallCount() int {
	fake.buildQueryResponseMutex.RLock()
	defer fake.buildQueryResponseMutex.RUnlock()
	return len(fake.buildQueryResponseArgsForCall)
}

func (fake *QueryResponseBuilder) BuildQueryResponseArgsForCall(i int) (*chaincode_test.TransactionContext, commonledger.ResultsIterator, string) {
	fake.buildQueryResponseMutex.RLock()
	defer fake.buildQueryResponseMutex.RUnlock()
	return fake.buildQueryResponseArgsForCall[i].txContext, fake.buildQueryResponseArgsForCall[i].iter, fake.buildQueryResponseArgsForCall[i].iterID
}

func (fake *QueryResponseBuilder) BuildQueryResponseReturns(result1 *pb.QueryResponse, result2 error) {
	fake.BuildQueryResponseStub = nil
	fake.buildQueryResponseReturns = struct {
		result1 *pb.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *QueryResponseBuilder) BuildQueryResponseReturnsOnCall(i int, result1 *pb.QueryResponse, result2 error) {
	fake.BuildQueryResponseStub = nil
	if fake.buildQueryResponseReturnsOnCall == nil {
		fake.buildQueryResponseReturnsOnCall = make(map[int]struct {
			result1 *pb.QueryResponse
			result2 error
		})
	}
	fake.buildQueryResponseReturnsOnCall[i] = struct {
		result1 *pb.QueryResponse
		result2 error
	}{result1, result2}
}

func (fake *QueryResponseBuilder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.buildQueryResponseMutex.RLock()
	defer fake.buildQueryResponseMutex.RUnlock()

	fake.buildQueryResponseWithMetaInfoMutex.RLock()
	defer fake.buildQueryResponseWithMetaInfoMutex.RUnlock()

	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *QueryResponseBuilder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
